wandb_version: 1

learning_rate:
  desc: null
  value: 0.002
weight_decay:
  desc: null
  value: 1.0e-05
architecture:
  desc: null
  value: ResNet-18
dataset:
  desc: null
  value: PTB-XL
epochs:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.11.6
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.38.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713701472.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.11.6
      5: 0.16.5
      6: 4.38.2
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
